export const difficultyLevels = [
  {
    level: 1,
    minScore: 0,
    maxScore: 1000,
    decimalCount: 1,
    chronoSpeed: 1.0,
    precisionMargin: 20,
    minTargetTime: 5,
    maxTargetTime: 5,
    circleVisibility: true,
    circleMargin: 0,
  },
  {
    level: 2,
    minScore: 1001,
    maxScore: 2000,
    decimalCount: 2,
    chronoSpeed: 1.2,
    precisionMargin: 15,
    minTargetTime: 3,
    maxTargetTime: 3,
    circleVisibility: true,
    circleMargin: 0,
  },
  {
    level: 3,
    minScore: 2001,
    maxScore: 3000,
    decimalCount: 3,
    chronoSpeed: 1.4,
    precisionMargin: 12,
    minTargetTime: 4,
    maxTargetTime: 6,
    circleVisibility: true,
    circleMargin: 0,
  },
  {
    level: 4,
    minScore: 3001,
    maxScore: 4000,
    decimalCount: 3,
    chronoSpeed: 1.6,
    precisionMargin: 10,
    minTargetTime: 4,
    maxTargetTime: 6,
    circleVisibility: false,
    circleMargin: 0,
  },
  {
    level: 5,
    minScore: 4001,
    maxScore: 5000,
    decimalCount: 3,
    chronoSpeed: 1.8,
    precisionMargin: 9,
    minTargetTime: 4,
    maxTargetTime: 6,
    circleVisibility: false,
    circleMargin: 0,
  },
  {
    level: 6,
    minScore: 5001,
    maxScore: 6000,
    decimalCount: 3,
    chronoSpeed: 2.0,
    precisionMargin: 8.5,
    minTargetTime: 3,
    maxTargetTime: 8,
    circleVisibility: false,
    circleMargin: 0,
  },
  {
    level: 7,
    minScore: 6001,
    maxScore: 7000,
    decimalCount: 3,
    chronoSpeed: 2.3,
    precisionMargin: 8,
    minTargetTime: 3,
    maxTargetTime: 8,
    circleVisibility: false,
    circleMargin: 0,
  },
  {
    level: 8,
    minScore: 7001,
    maxScore: 8000,
    decimalCount: 3,
    chronoSpeed: 2.6,
    precisionMargin: 7.5,
    minTargetTime: 3,
    maxTargetTime: 8,
    circleVisibility: false,
    circleMargin: 0,
  },
  {
    level: 9,
    minScore: 8001,
    maxScore: 9000,
    decimalCount: 3,
    chronoSpeed: 2.9,
    precisionMargin: 7,
    minTargetTime: 3,
    maxTargetTime: 8,
    circleVisibility: false,
    circleMargin: 0,
  },
  {
    level: 10,
    minScore: 9001,
    maxScore: 10000,
    decimalCount: 3,
    chronoSpeed: 3.2,
    precisionMargin: 6.5,
    minTargetTime: 3,
    maxTargetTime: 8,
    circleVisibility: true,
    circleMargin: 0.01,
  },
  {
    level: 11,
    minScore: 10001,
    maxScore: 11000,
    decimalCount: 3,
    chronoSpeed: 3.6,
    precisionMargin: 6,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.015,
  },
  {
    level: 12,
    minScore: 11001,
    maxScore: 12000,
    decimalCount: 3,
    chronoSpeed: 4.0,
    precisionMargin: 5.5,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.02,
  },
  {
    level: 13,
    minScore: 12001,
    maxScore: 13000,
    decimalCount: 3,
    chronoSpeed: 4.5,
    precisionMargin: 5,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.03,
  },
  {
    level: 14,
    minScore: 13001,
    maxScore: 14000,
    decimalCount: 3,
    chronoSpeed: 5.0,
    precisionMargin: 4.5,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.04,
  },
  {
    level: 15,
    minScore: 14001,
    maxScore: 15000,
    decimalCount: 3,
    chronoSpeed: 5.6,
    precisionMargin: 4,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.05,
  },
  {
    level: 16,
    minScore: 15001,
    maxScore: 16000,
    decimalCount: 3,
    chronoSpeed: 6.2,
    precisionMargin: 3.5,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.06,
  },
  {
    level: 17,
    minScore: 16001,
    maxScore: 17000,
    decimalCount: 3,
    chronoSpeed: 7.0,
    precisionMargin: 3,
    minTargetTime: 2.5,
    maxTargetTime: 10,
    circleVisibility: true,
    circleMargin: 0.07,
  },
  {
    level: 18,
    minScore: 17001,
    maxScore: 18000,
    decimalCount: 3,
    chronoSpeed: 7.8,
    precisionMargin: 2.5,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.08,
  },
  {
    level: 19,
    minScore: 18001,
    maxScore: 19000,
    decimalCount: 3,
    chronoSpeed: 8.7,
    precisionMargin: 2,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.09,
  },
  {
    level: 20,
    minScore: 19001,
    maxScore: 20000,
    decimalCount: 3,
    chronoSpeed: 9.7,
    precisionMargin: 1.5,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.1,
  },
  {
    level: 21,
    minScore: 20001,
    maxScore: 21000,
    decimalCount: 3,
    chronoSpeed: 10.7,
    precisionMargin: 1,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.11,
  },
  {
    level: 22,
    minScore: 21001,
    maxScore: 22000,
    decimalCount: 3,
    chronoSpeed: 11.7,
    precisionMargin: 0.9,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.12,
  },
  {
    level: 23,
    minScore: 22001,
    maxScore: 23000,
    decimalCount: 3,
    chronoSpeed: 12.8,
    precisionMargin: 0.8,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.13,
  },
  {
    level: 24,
    minScore: 23001,
    maxScore: 24000,
    decimalCount: 3,
    chronoSpeed: 13.9,
    precisionMargin: 0.7,
    minTargetTime: 2,
    maxTargetTime: 20,
    circleVisibility: true,
    circleMargin: 0.14,
  },
  {
    level: 25,
    minScore: 24001,
    maxScore: 25000,
    decimalCount: 3,
    chronoSpeed: 15.0,
    precisionMargin: 0.6,
    minTargetTime: 2,
    maxTargetTime: 60,
    circleVisibility: true,
    circleMargin: 0.15,
  },
  {
    level: 26,
    minScore: 25001,
    maxScore: 26000,
    decimalCount: 3,
    chronoSpeed: 16.0,
    precisionMargin: 0.5,
    minTargetTime: 2,
    maxTargetTime: 60,
    circleVisibility: true,
    circleMargin: 0.17,
  },
  {
    level: 27,
    minScore: 26001,
    maxScore: 27000,
    decimalCount: 3,
    chronoSpeed: 17.0,
    precisionMargin: 0.4,
    minTargetTime: 2,
    maxTargetTime: 60,
    circleVisibility: true,
    circleMargin: 0.19,
  },
  {
    level: 28,
    minScore: 27001,
    maxScore: 28000,
    decimalCount: 3,
    chronoSpeed: 18.0,
    precisionMargin: 0.3,
    minTargetTime: 2,
    maxTargetTime: 60,
    circleVisibility: true,
    circleMargin: 0.21,
  },
  {
    level: 29,
    minScore: 28001,
    maxScore: 29000,
    decimalCount: 3,
    chronoSpeed: 19.0,
    precisionMargin: 0.2,
    minTargetTime: 2,
    maxTargetTime: 60,
    circleVisibility: true,
    circleMargin: 0.23,
  },
  {
    level: 30,
    minScore: 29001,
    maxScore: Infinity,
    decimalCount: 3,
    chronoSpeed: 20.0,
    precisionMargin: 0.1,
    minTargetTime: 2,
    maxTargetTime: 60,
    circleVisibility: true,
    circleMargin: 0.25,
  },
];

export function getDifficultyParams(score) {
  for (let i = difficultyLevels.length - 1; i >= 0; i--) {
    const level = difficultyLevels[i];
    if (score >= level.minScore && score <= level.maxScore) {
      return level;
    }
  }
  console.error(`No difficulty level found for score: ${score}`);
  return null;
}
